### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by kangdengfeng** [JuZiSang/blog#8]
这是用的Mysql数据库吗？因为没有看到可执行的数据库脚本，想问下怎么才知道数据库的结构。

**Comment by JuZiSang** [comment]
抱歉，这个还没有做完。server/model中可以看到表结构

**Comment by kangdengfeng** [comment]
非常感谢您的回复，您说的没做完是指哪方面呀？哈哈哈，因为最近正在学习，不知道能不能有什么可以帮忙推进的~

**Comment by kangdengfeng** [comment]
非常感谢~好好学习，天天向上。哈哈哈~
